theme = "catppuccin_mocha"

[editor]
mouse = true
line-number = "relative"
rulers = [80]
cursorline = true
bufferline = "always"
true-color = true
color-modes =true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

# ### https://docs.helix-editor.com/master/configuration.html#editorwhitespace-section
# [editor.whitespace.render]
# space = "all"
# tab = "all"
# newline = "none"

# [editor.whitespace.characters]
# space = " "
# nbsp = "⍽"    # Espacio no divisible
# tab = "→"
# newline = "⏎"
# tabpad = "·"  # Las pestañas se verán como "→···" (dependiendo del ancho de la pestaña)

[editor.statusline]
left = [ "mode", "spinner", "diagnostics" ]
center = [ "file-name", "separator", "version-control", "separator" ]
right = [ "position", "position-percentage", "total-line-numbers" ]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "╎" # Algunos caracteres que funcionan bien: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.auto-save]
focus-lost = true


# keymaps
[keys.normal]
C-s = ":w"
C-o = ":open ~/.config/helix/config.toml"
C-r = ":config-reload"
esc = ["collapse_selection", "keep_primary_selection"]

#"S-g" = ""
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
space.c = "toggle_comments"
space.l = "goto_line_end"
space.h = "goto_line_start"
g.c = "goto_line_start"
C-A = "toggle_comments"

# move line up or down
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]

V = ["select_mode", "extend_to_line_bounds"]
G = "goto_last_line"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
y = "yank_main_selection_to_clipboard"
D = ["extend_to_line_bounds", "delete_selection"]

[keys.insert]
k = { j = "normal_mode" } # maps `kj` to exit insert mode

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
G = "goto_last_line"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
y = "yank_main_selection_to_clipboard"
space.c = "toggle_comments"
